name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 🔨 set up .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 🧪 run tests
      run: |
        cd ./tests/BaroquenMelody.Library.Tests/
        dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        cp TestResults/*/coverage.opencover.xml .    

    - name: 💌 publish code coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: /home/runner/work/baroquen-melody/baroquen-melody/tests/BaroquenMelody.Library.Tests/coverage.opencover.xml
        fail_ci_if_error: true
